(************************************************)
(* 						*)
(*	  SuperVGA S3 BGI driver defines	*)
(*		Copyright (c) 1992		*)
(*	    Jordan Hargraphix Software		*)
(*						*)
(************************************************)

(* These are the currently supported modes *)
const
  SVGAS3_640x480x256	= 0;
  SVGAS3_800x600x256	= 1;
  SVGAS3_1024x768x256 	= 2;
  SVGAS3_800x600x16	= 3;
  SVGAS3_1024x768x16	= 4;
  SVGAS3_1280x960x16	= 5;
  SVGAS3_1280x1024x16	= 6;
  SVGAS3_640x480x32768	= 7;

