(************************************************)
(* 						*)
(*	 SuperVGA 24-bit BGI driver defines	*)
(*		Copyright (c) 1991		*)
(*	    Jordan Hargraphix Software		*)
(*						*)
(************************************************)

(* These are the currently supported modes *)
const
  SVGA320x200x24_bit	= 0;	(* 320x200x24-bit TrueColor VGA *)
  SVGA640x350x24_bit	= 1;	(* 640x350x24-bit TrueColor VGA *)
  SVGA640x400x24_bit	= 2;	(* 640x400x24-bit TrueColor VGA *)
  SVGA640x480x24_bit	= 3;	(* 640x480x24-bit TrueColor VGA *)
  SVGA800x600x24_bit	= 4;	(* 800x600x24-bit TrueColor VGA *)
  SVGA1024x768x24_bit	= 5;	(* 1024x768x24-bit TrueColor VGA *)
  SVGA1280x1024x24_bit	= 6;	(* 1280x1024x24-bit TrueColor VGA *)

