(************************************************)
(* 						*)
(*	 SuperVGA 65536 BGI driver defines	*)
(*		Copyright (c) 1993		*)
(*	    Jordan Hargraphix Software		*)
(*						*)
(************************************************)

(* These are the currently supported modes *)
const
  SVGA320x200x65536	= 0;	(* 320x200x65536 HiColor VGA *)
  SVGA640x350x65536	= 1;	(* 640x350x65536 HiColor VGA *)
  SVGA640x400x65536	= 2;	(* 640x400x65536 HiColor VGA *)
  SVGA640x480x65536	= 3;	(* 640x480x65536 HiColor VGA *)
  SVGA800x600x65536	= 4;	(* 800x600x65536 HiColor VGA *)
  SVGA1024x768x65536	= 5;	(* 1024x768x65536 HiColor VGA *)
  SVGA1280x1024x65536	= 6;	(* 1280x1024x65536 HiColor VGA *)

