(************************************************)
(* 						*)
(*	  SuperVGA 16 BGI driver defines	*)
(*		Copyright (c) 1991		*)
(*	    Jordan Hargraphix Software		*)
(*						*)
(************************************************)

(* These are the currently supported modes *)
const
 TWK704x528x16		= 0;    (* 704x528x16 Tweaked VGA *)
 TWK720x540x16		= 1;	(* 720x540x16 Tweaked VGA *)
 TWK736x552x16		= 2;	(* 736x552x16 Tweaked VGA *)
 TWK752x564x16		= 3;	(* 752x564x16 Tweaked VGA *)
 TWK784x588x16		= 4;	(* 784x588x16 Tweaked VGA *)
 TWK800x600x16		= 5;	(* 800x600x16 Tweaked VGA *)

