(************************************************)
(* 						*)
(*	  Tweaked 256 BGI driver defines	*)
(*		Copyright (c) 1991		*)
(*	    Jordan Hargraphix Software		*)
(*						*)
(************************************************)

(* These are the currently supported modes *)
const
  TWK320x400x256	= 0;
  TWK320x480x256	= 1;
  TWK360x480x256	= 2;
  TWK376x564x256	= 3;
  TWK400x564x256	= 4;
  TWK400x600x256	= 5;
  TWK320x240x256	= 6;

